[[main]]
 name = "Posts"
 pageRef = "/posts"
 weight = 1

[[main]]
 name = "Topic"
 pageRef = "/topic"
 weight = 2

[[main]]
 name = "About"
 pageRef = "/about"
 weight = 3

[[main]]
 name = "Misc"
 pageRef = "/misc"
 weight = 4

[[footer]]
none = "none"
